@Library('polaris')
import ca.bc.gov.nrids.polaris.BrokerIntention
import ca.bc.gov.nrids.polaris.JenkinsUtil
import ca.bc.gov.nrids.polaris.Podman
import ca.bc.gov.nrids.polaris.Vault

def env_short = JenkinsUtil.convertLongEnvToShort("${params.environment}")
def intention
def podman

pipeline {
    agent {
        label Podman.AGENT_LABEL_APP
    }
    environment {
        TARGET_ENV = "${params.environment}"
        GH_REPO = "${params.githubRepo}"
        OWNER = GH_REPO.substring(0, GH_REPO.lastIndexOf("/"))
        REPO = GH_REPO.substring(GH_REPO.lastIndexOf("/") + 1)
        GIT_BRANCH = "${params.gitBranch}"
        LIQUIBASE_FRAMEWORK_DIR = "nrmcfs-liquibase-framework"
        LIQUIBASE_FRAMEWORK_BRANCH = "${params.liquibaseFrameworkBranch != null && params.liquibaseFrameworkBranch != "" ? params.liquibaseFrameworkBranch : "main"}"
        LIQUIBASE_SEARCH_PATH = "${params.liquibaseSearchPath != null && params.liquibaseSearchPath != "" ? params.liquibaseSearchPath : "/liquibase/changelog"}"
        SEM_VERSION = "${params.semanticVersion}"
        TAG_VERSION = "v${SEM_VERSION}"
        SERVICE_PROJECT = "${params.serviceProject}"
        SERVICE_NAME = "${params.serviceName}"
        PODMAN_WORKDIR =  "/liquibase/changelog"
        TMP_VOLUME = "liquibase.${UUID.randomUUID().toString()[0..7]}"
        TMP_OUTPUT_FILE = "liquibase.stderr.${UUID.randomUUID().toString()[0..7]}"
        ONFAIL_GREP_PATTERN = "^WARNING"
        NOTIFICATION_RECIPIENTS = "${params.notificationRecipients}"
        EVENT_PROVIDER = "${params.eventProvider}"
        PODMAN_REGISTRY = "docker.io"
        CONTAINER_IMAGE_CONSUL_TEMPLATE = "hashicorp/consul-template"
        CONTAINER_IMAGE_LIQUBASE = "liquibase/liquibase:4.21.1"
        HOST = "freight.bcgov"
        PODMAN_USER = "wwwadm"
        NR_DATABASE_MIGRATION_ROLE_ID = credentials('knox-nr-database-migration-prod-role-id')
        NR_BROKER_TOKEN = credentials('nr-broker-jwt')
        DB_ROLE_ID = credentials("knox-${params.serviceProject}-${params.serviceName}-${env_short}-role-id")
        AUTHFILE = "auth.json"
    }
    stages {
        stage('Banner') {
            steps {
	            script {
                    echo "==================="
                    echo "NR Polaris Pipeline"
                    echo "==================="
                    echo ""
                    echo "NRMCFS database migration pipeline"
                    echo ""
                    echo "Jenkinsfile: https://github.com/bcgov-nr/polaris-pipelines/blob/main/pipelines/nrmcfs-database-migration"
                }
            }
        }
        stage('Setup') {
            steps {
                script {
                    env.DRY_RUN = params.dryRun ? 'true' : 'false'
                    env.CAUSE_USER_ID = JenkinsUtil.getCauseUserId(currentBuild)
                    env.CURRENT_DIR = sh(
                        returnStdout: true,
                        script: 'pwd'
                    ).trim()
                    env.LIQUIBASE_FRAMEWORK_PATH = "${TMP_VOLUME}/nrmcfs-liquibase-framework"

                }
                sh "mkdir -p ${TMP_VOLUME} && chmod 775 ${TMP_VOLUME}"
                echo "Current directory: ${env.CURRENT_DIR}"
                echo "Liquibase search path: ${LIQUIBASE_SEARCH_PATH}"
                echo "Liquibase framework path: ${LIQUIBASE_FRAMEWORK_PATH}"
                echo "Dry run: ${env.DRY_RUN}"
            }
        }
        stage('Get github token') {
            steps {
                script {
                    // open intention to get github app creds
                    intention = new BrokerIntention(NR_BROKER_TOKEN, readJSON(file: "scripts/intention-github-app.json"))
                    intention.setEventDetails(
                        userName: env.CAUSE_USER_ID,
                        provider: env.EVENT_PROVIDER,
                        url: env.BUILD_URL,
                        serviceName: env.SERVICE_NAME,
                        serviceProject: env.SERVICE_PROJECT,
                        environment: "tools"
                    )
                    intention.open()
                    intention.startAction("login")
                    def vaultGhToken = intention.provisionToken("login", NR_DATABASE_MIGRATION_ROLE_ID)
                    def vaultGhApp = new Vault(vaultGhToken)
                    def ghAppCreds = vaultGhApp.read("apps/data/prod/db-pipeline/nr-database-migration/github_app")
                    env.APP_ID = ghAppCreds['gh_app_id']
                    env.INSTALLATION_ID = ghAppCreds['gh_installation_id']
                    env.PRIVATE_KEY = ghAppCreds['gh_private_key']
                    // generate github app jwt
                    env.GENERATED_JWT = sh(
                        returnStdout: true,
                        script: 'set +x ; scripts/generate_jwt.sh'
                    )
                    env.GH_TOKEN = sh(
                        returnStdout: true,
                        script: 'set +x ; scripts/get_installation_token.sh'
                    )
                    intention.endAction("login")
                    intention.close(true)
                }
            }
        }
        stage('Checkout for deployment to development') {
            when { environment name: 'TARGET_ENV', value: 'development' }
            steps {
                script {
                    wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: env.GH_TOKEN, password: GH_TOKEN]]]) {
                        sh "GH_TOKEN=${GH_TOKEN} gh repo clone ${OWNER}/${REPO} ${TMP_VOLUME} -- --branch=${GIT_BRANCH}"
                    }
                }
            }
        }
        stage('Checkout for deployment to test') {
            when { environment name: 'TARGET_ENV', value: 'test' }
            steps {
                script {
                    wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: env.GH_TOKEN, password: GH_TOKEN]]]) {
                        sh "GH_TOKEN=${GH_TOKEN} gh repo clone ${OWNER}/${REPO} ${TMP_VOLUME} -- --branch=${TAG_VERSION}-development"
                    }
                }
            }
        }
        stage('Checkout for deployment to production') {
            when { environment name: 'TARGET_ENV', value: 'production' }
            steps {
                script {
                    wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: env.GH_TOKEN, password: GH_TOKEN]]]) {
                        sh "GH_TOKEN=${GH_TOKEN} gh repo clone ${OWNER}/${REPO} ${TMP_VOLUME} -- --branch=${TAG_VERSION}-test"
                    }
                }
            }
        }
        stage('Generate Liquibase properties') {
            steps {
                script {
                    // open intention to get registry and db creds
                    intention = new BrokerIntention(NR_BROKER_TOKEN, readJSON(file: 'scripts/intention-database.json'))
                    intention.setEventDetails(
                        userName: env.CAUSE_USER_ID,
                        provider: env.EVENT_PROVIDER,
                        url: env.BUILD_URL,
                        serviceName: env.SERVICE_NAME,
                        serviceProject: env.SERVICE_PROJECT,
                        environment: env.TARGET_ENV
                    )
                    intention.open()
                    intention.startAction("login")
                    def vaultToken = intention.provisionToken("login", NR_DATABASE_MIGRATION_ROLE_ID)
                    def vault = new Vault(vaultToken)
                    def registryCreds = vault.read('apps/data/prod/db-pipeline/nr-database-migration/artifactory')
                    env.REGISTRY_USERNAME = registryCreds['sa_username']
                    env.REGISTRY_PASSWORD = registryCreds['sa_password']
                    env.APP_VAULT_TOKEN = intention.provisionToken("database", DB_ROLE_ID)
                    podman = new Podman(this, null)
                    podman.login(authfile: "${TMP_VOLUME}/${AUTHFILE}", options: "-u ${env.REGISTRY_USERNAME} -p ${env.REGISTRY_PASSWORD}")
                    wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: env.APP_VAULT_TOKEN, password: APP_VAULT_TOKEN]]]) {
                        podman.run("${CONTAINER_IMAGE_CONSUL_TEMPLATE}",
                            authfile: "${TMP_VOLUME}/${AUTHFILE}",
                            options: "--rm \
                                --security-opt label=disable \
                                --userns keep-id \
                                -v \$(pwd)/${TMP_VOLUME}:${PODMAN_WORKDIR} \
                                -v \$(pwd)/scripts/config.hcl:${PODMAN_WORKDIR}/config.hcl \
                                -e TARGET_ENV_SHORT=${env_short} \
                                -e LIQUIBASE_SEARCH_PATH=${LIQUIBASE_SEARCH_PATH} \
                                -e PODMAN_WORKDIR=${PODMAN_WORKDIR} \
                                -e VAULT_TOKEN=${APP_VAULT_TOKEN}",
                            command: "-config '/liquibase/changelog/config.hcl' \
                                -template '/liquibase/changelog/liquibase.properties.tpl:${PODMAN_WORKDIR}/liquibase.properties' \
                                -once",
                            returnStatus: true
                        )
                    }
                    intention.endAction("login")
                }
            }
        }
        stage('Checkout NRMCFS Liquibase framework') {
            steps {
                script {
                    wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: env.GH_TOKEN, password: GH_TOKEN]]]) {
                        sh "GH_TOKEN=${GH_TOKEN} gh repo clone bcgov-nr/nrmcfs-liquibase-framework ${LIQUIBASE_FRAMEWORK_PATH} -- --branch=${LIQUIBASE_FRAMEWORK_BRANCH}"
                    }
                }
            }
        }
        stage('Get status') {
            steps {
                script {
                    sh "${LIQUIBASE_FRAMEWORK_PATH}/scripts/status.sh"
                }
            }
        }
        stage('Dry run') {
            when { expression { return params.dryRun == true } }
            steps {
                script {
                    sh "${LIQUIBASE_FRAMEWORK_PATH}/scripts/dry-run.sh"
                }
            }
        }
        stage('Pre-migration') {
            when { expression { return params.dryRun == false } }
            steps {
                script {
                    sh "${LIQUIBASE_FRAMEWORK_PATH}/scripts/pre-migration.sh"
                }
            }
        }
        stage('Update database') {
            when { expression { return params.dryRun == false } }
            steps {
                script {
                    sh "${LIQUIBASE_FRAMEWORK_PATH}/scripts/update.sh"
                }
            }
        }
        stage('Post-migration') {
            when { expression { return params.dryRun == false } }
            steps {
                script {
                    sh "${LIQUIBASE_FRAMEWORK_PATH}/scripts/post-migration.sh"
                    intention.endAction("database")
                    podman.logout(authfile: "${TMP_VOLUME}/${AUTHFILE}")
                }
            }
        }
        stage('Podman logout') {
            steps {
                script {
                    intention.endAction("database")
                    podman.logout(authfile: "${TMP_VOLUME}/${AUTHFILE}")
                }
            }
        }
    }
    post {
        success {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println intention.close(true)
                    }
                }
            }
        }
        unstable {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println intention.close(false)
                    }
                }
            }
        }
        failure {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println intention.close(false)
                    }
                }
            }
        }
        aborted {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println intention.close(false)
                    }
                }
            }
        }
        always {
            node(Podman.AGENT_LABEL_APP) {
                cleanWs(
                    cleanWhenAborted: true,
                    cleanWhenFailure: false,
                    cleanWhenSuccess: true,
                    cleanWhenUnstable: false,
                    deleteDirs: true
                )
                script {
                    if (TMP_VOLUME.startsWith('liquibase.')) {
                        echo "Delete temporary directory: ${TMP_VOLUME}"
                        sh "rm --preserve-root -rf '${CURRENT_DIR}/${TMP_VOLUME}'"
                    } else {
                        echo "Skipping deletion of temporary directory: ${TMP_VOLUME}"
                    }
                    if (TMP_OUTPUT_FILE.startsWith('liquibase.stderr.')) {
                        echo "Delete temporary output file: ${TMP_OUTPUT_FILE}"
                        sh "rm -f '${CURRENT_DIR}/${TMP_OUTPUT_FILE}'"
                    } else {
                        echo "Skipping deletion of temporary output file: ${TMP_OUTPUT_FILE}"
                    }
                }
            }
        }
    }
}
