@Library('polaris@v2.0.0')
import ca.bc.gov.nrids.polaris.Podman
import ca.bc.gov.nrids.polaris.BrokerIntention
import ca.bc.gov.nrids.polaris.Vault
import ca.bc.gov.nrids.polaris.JenkinsUtil

def intention
def podman

pipeline {
    agent none
    stages {
        stage('Initialize') {
            steps {
                script {
                    // Set the build display name
                    currentBuild.displayName = "#${BUILD_NUMBER} - ${params.gitBranch} - ${params.envLong}"
                }
            }
        }
        stage('Banner') {
            steps {
	            script {
                    echo "==================="
                    echo "NR Polaris Pipeline"
                    echo "==================="
                    echo ""
                    echo "Standard Jasper report deployment pipeline"
                    echo ""
                    echo "Jenkinsfile: https://github.com/bcgov-nr/polaris-pipelines/blob/main/pipelines/reports-jasper"
                    echo "Ansible Polaris collection: https://github.com/bcgov/nr-polaris-collection"
                    echo ""
                    echo "Developers are expected to review the documentation of all roles used by their Ansible playbook file."
                }
            }
        }
        stage('Checkout catalog') {
            agent {
                label Podman.AGENT_LABEL_APP
            }
            environment {
                GIT_REPO = "${params.gitRepo}"
                GIT_BRANCH = "${params.gitTag != null && params.gitTag != "" ? params.gitTag : params.gitBranch}"
                GITHUB_PRIVATE_REPO = "${params.githubToken != null && params.githubToken != "" ? 'true' : ''}"
            }
            steps {
                script {
                    sh 'rm -rf app'
                    if (env.GITHUB_PRIVATE_REPO) {
                        env.GITHUB_USER = "${params.githubUser}"
                        env.GITHUB_TOKEN = "${params.githubToken}"
                        wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: env.GITHUB_TOKEN, password: GITHUB_TOKEN]]]) {
                            sh '''
                                git config --global advice.detachedHead false
                                git clone -q --no-checkout https://${GITHUB_USER}:${GITHUB_TOKEN}@${GIT_REPO} app
                                cd app
                                git sparse-checkout init --cone
                                git checkout ${GIT_BRANCH}
                            '''
                        }
                    } else {
                        sh '''
                            git config --global advice.detachedHead false
                            git clone -q --no-checkout https://${GIT_REPO} app
                            cd app
                            git sparse-checkout init --cone
                            git checkout ${GIT_BRANCH}
                        '''
                    }
                    def backstage = readYaml (file: 'app/catalog-info.yaml')
                    echo backstage['metadata']['playbook.io.nrs.gov.bc.ca/playbookPath'][0]
                }
            }
        }
        stage('Sparse checkout app') {
            agent {
                label Podman.AGENT_LABEL_APP
            }
            steps {
                script {
                    sh '''
                        cd app
                        PLAYBOOKS_PATH="playbooks"
                        JASPER_PATH="jasper-server"
                        git sparse-checkout set .jenkins "$PLAYBOOKS_PATH" "$JASPER_PATH"
                    '''
                }
            }
        }
        stage('Deploy to environment') {
            agent {
                label Podman.AGENT_LABEL_APP
            }
            environment {
                PROJECT = "${params.project}"
                COMPONENT = "${params.component}"
                GIT_REPO = "${params.gitRepo}"
                GIT_BRANCH = "${params.gitBranch}"
                ENV_LONG = "${params.envLong}"
                EVENT_PROVIDER = "${params.eventProvider}"
                GITHUB_RUNID= "${params.githubRunId}"
                TRIGGER_URL = "${params.triggerUrl}"
                HTTP_PROXY = "${params.envLong == 'production' ? 'http://forwardproxy.nrs.bcgov:23128' : 'http://test-forwardproxy.nrs.bcgov:23128'}"
                NO_PROXY = "knox.io.nrs.gov.bc.ca,dlvrapps.nrs.bcgov,testapps.nrs.bcgov,apps.nrs.bcgov"
                AUTHFILE = "auth.json"
                ANSIBLE_COLLECTION_VERSION = "${params.ansibleCollectionBranchTag != null && params.ansibleCollectionBranchTag != "" ? ",${params.ansibleCollectionBranchTag}" : ",main"}"
                PODMAN_ANSIBLE_COLLECTION_URL = "github.com/bcgov/nr-polaris-collection.git#polaris/deploy${env.ANSIBLE_COLLECTION_VERSION}"
                PODMAN_ANSIBLE_COLLECTION_PATH = "./collections/ansible_collections"
                CAUSE_USER_ID = "${params.userId != null && params.userId != "" ? params.userId : "github@internal"}"
                CONFIG_ROLE_ID = credentials("knox-jasper-jasper-reports-${params.jasperServerInstance}-prod-role-id")
            }
            steps {
                script {
                    try {
                        echo "Do ${env.ENV_LONG} deployment"
                        env.ENV_SHORT = JenkinsUtil.convertLongEnvToShort("${params.envLong}")
                        def triggerId = "${env.COMPONENT} ${env.GITHUB_RUNID}"
                        intention = new BrokerIntention("${params.brokerJwt}", readJSON(file: "app/.jenkins/${env.COMPONENT}-intention.json"))
                        intention.setEventDetails(
                            userName: env.CAUSE_USER_ID,
                            url: env.BUILD_URL,
                            provider: env.EVENT_PROVIDER,
                            triggerId: triggerId,
                            triggerUrl: env.TRIGGER_URL,
                            environment: env.ENV_LONG
                        )
                        intention.open()
                        intention.startAction("login")
                        def vaultToken = intention.provisionToken("login", CONFIG_ROLE_ID)
                        def vault = new Vault(vaultToken)
                        vault.readToObject("apps/data/prod/jasper/jasper-reports-${params.jasperServerInstance}/artifactory", env)
                        vault.readToObject("apps/data/prod/jasper/jasper-reports-${params.jasperServerInstance}/${env.ENV_SHORT}", env, keyTransform: { key -> 'PODMAN_' + key })
                        intention.startAction("configure")
                        def appRoleId = ""
                        try {
                            withCredentials([string(credentialsId: "knox-${params.project}-${params.component}-${env.ENV_SHORT}-role-id", variable: 'APP_ROLE_ID')]) {
                                appRoleId = env.APP_ROLE_ID
                            }
                        } catch (Exception e) {
                            echo "ROLE ID not found - continue without it"
                        }
                        def vaultAppToken = intention.provisionToken("configure", appRoleId)
                        def vaultApp = new Vault(vaultAppToken)
                        vaultApp.readToObject("apps/data/${env.ENV_SHORT}/${env.PROJECT}/${env.COMPONENT}/${env.ENV_LONG}", env, keyTransform: { key -> 'PODMAN_' + key })
                        intention.openResponse.actions.each { key, value ->
                            env."ACTION_TOKEN_${key.toUpperCase()}" = "${value.token}"
                        }
                        podman = new Podman(this)
                        podman.login(authfile: "${env.AUTHFILE}", options: "-u ${env.sa_username} -p ${env.sa_password}")
                        podman.run("willhallonline/ansible:2.17-alpine-3.20",
                            authfile: "${env.AUTHFILE}",
                            options: "-v \$(pwd):/ansible -e PODMAN_*",
                            command: 'ansible-galaxy collection install git+https://${PODMAN_ANSIBLE_COLLECTION_URL} -p ${PODMAN_ANSIBLE_COLLECTION_PATH}')
                        podman.run("willhallonline/ansible:2.17-alpine-3.20",
                            authfile: "${env.AUTHFILE}",
                            options: "-v \$(pwd)/collections:/ansible/app/playbooks/collections -v \$(pwd)/app:/ansible/app -e PODMAN_*",
                            command: "ansible-playbook app/playbooks/jasper-reports.yaml --extra-vars \"jasper_env=${env.ENV_SHORT}\" --tags create_package")
                        podman.run("willhallonline/ansible:2.17-alpine-3.20",
                            authfile: "${env.AUTHFILE}",
                            options: "-v \$(pwd)/collections:/ansible/app/playbooks/collections -v \$(pwd)/app:/ansible/app -e PODMAN_*",
                            command: "ansible-playbook app/playbooks/jasper-reports.yaml --extra-vars \"jasper_env=${env.ENV_SHORT}\" --tags deploy_package")
                        podman.run("willhallonline/ansible:2.17-alpine-3.20",
                            authfile: "${env.AUTHFILE}",
                            options: "-v \$(pwd)/collections:/ansible/app/playbooks/collections -v \$(pwd)/app:/ansible/app -e PODMAN_*",
                            command: "ansible-playbook app/playbooks/jasper-reports.yaml --extra-vars \"jasper_env=${env.ENV_SHORT}\" --tags delete_staging_dir")
                        podman.logout(authfile: "${env.AUTHFILE}")
                        vaultApp.revokeToken()
                        vault.revokeToken()
                        intention.endAction("configure")
                        intention.endAction("login")
                        println intention.close(true)
                        intention = null
                    } catch (IllegalStateException ex) {
                        echo "IllegalStateException occurred: $ex"
                        currentBuild.result = 'FAILURE'
                        error('Quitting')
                    } catch (IllegalArgumentException ex) {
                        echo "IllegalArgumentException occurred: $ex"
                        currentBuild.result = 'FAILURE'
                        error('Quitting')
                    } catch (Exception ex) {
                        echo "Other exception occurred: $ex"
                        currentBuild.result = 'FAILURE'
                        error('Quitting')
                    }
                }
            }
        }
    }
    post {
        unstable {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println intention.close(false)
                    }
                }
            }
        }
        failure {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println intention.close(false)
                    }
                }
            }
        }
        aborted {
            node(Podman.AGENT_LABEL_APP) {
                script {
                    if (intention) {
                        println  intention.close(false)
                    }
                }
            }
        }
        always {
            node(Podman.AGENT_LABEL_APP) {
                cleanWs(
                    cleanWhenAborted: true,
                    cleanWhenFailure: false,
                    cleanWhenSuccess: true,
                    cleanWhenUnstable: false,
                    deleteDirs: true
                )
            }
        }
    }
}
